linters:
  fast: false
  enable:
    - misspell
    - gosec
    - godot
linters-settings:
  errcheck:
    check-type-assertions: true
  misspell:
    locale: US
    ignore-words: []
issues:
  exclude:
    - SA3000
