before:
  hooks:
    - go mod download
    - go mod tidy
builds:
  -
    id: runbk-darwin
    ldflags:
      - -s -w -X github.com/k1LoW/runbk.version={{.Version}} -X github.com/k1LoW/runbk.commit={{.FullCommit}} -X github.com/k1LoW/runbk.date={{.Date}} -X github.com/k1LoW/runbk/version.Version={{.Version}}
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/runbk/main.go
  -
    id: runbk-linux
    ldflags:
      - -s -w -X github.com/k1LoW/runbk.version={{.Version}} -X github.com/k1LoW/runbk.commit={{.FullCommit}} -X github.com/k1LoW/runbk.date={{.Date}} -X github.com/k1LoW/runbk/version.Version={{.Version}}
      - -linkmode external
      - -extldflags '-static'
    env:
      - CGO_ENABLED=1
      - CC=x86_64-unknown-linux-gnu-gcc # brew install messense/macos-cross-toolchains/x86_64-unknown-linux-gnu
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/runbk/main.go
archives:
  -
    id: runbk-archive
    name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format_overrides:
      - goos: darwin
        format: zip
    files:
      - CREDITS
      - README.md
      - CHANGELOG.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}-next"
changelog:
  skip: true
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
dockers:
  -
    goos: linux
    goarch: amd64
    image_templates:
      - 'ghcr.io/k1low/runbk:v{{ .Version }}'
      - 'ghcr.io/k1low/runbk:latest'
    dockerfile: Dockerfile
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/k1LoW/runbk"
      - "--platform=linux/amd64"
    extra_files:
      - scripts/entrypoint.sh
brews:
  -
    name: runbk
    tap:
      owner: k1LoW
      name: homebrew-tap
    commit_author:
      name: k1LoW
      email: k1lowxb@gmail.com
    homepage: https://github.com/k1LoW/runbk
    description: runbk is a tool for running operations following a scenario.
    license: MIT
    install: |
      bin.install 'runbk'
      output = Utils.safe_popen_read("#{bin}/runbk", 'completion', 'bash')
      (bash_completion/'runbk').write output
      output = Utils.safe_popen_read("#{bin}/runbk", 'completion', 'zsh')
      (zsh_completion/'_runbk').write output
nfpms:
  -
    id: runbk-nfpms
    file_name_template: "{{ .ProjectName }}_{{ .Version }}-1_{{ .Arch }}"
    builds:
      - runbk-linux
    homepage: https://github.com/k1LoW/runbk
    maintainer: Ken'ichiro Oyama <k1lowxb@gmail.com>
    description: runbk is a tool for running operations following a scenario.
    license: MIT
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin
    epoch: 1
